require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/Documentation:
  Enabled: false